In [1]:
import pandas as pd

In [2]:
fixtures_df = pd.read_csv("data/2026/matches.csv")
teams_df = pd.read_csv("data/2026/teams.csv")

In [3]:
fixtures_df.head()

,id,match_number,home_team_id,away_team_id,city_id,stage_id,kickoff_at,match_label
0,1,1,1.0,2.0,15,1,2026-06-11 15:00:00-06,Group A
1,2,2,3.0,4.0,14,1,2026-06-11 22:00:00-06,Group A
2,3,3,5.0,6.0,12,1,2026-06-12 15:00:00-04,Group B
3,4,4,13.0,14.0,6,1,2026-06-12 21:00:00-07,Group D
4,5,5,7.0,8.0,10,1,2026-06-13 15:00:00-07,Group B

In [4]:
teams_df.head()

   id     team_name fifa_code group_letter  is_placeholder
0   1        Mexico       MEX            A           False
1   2  South Africa       RSA            A           False
2   3   South Korea       KOR            A           False
3   4       Czechia       CZE            A            True
4   5        Canada       CAN            B           False

In [5]:
for index, team_row in teams_df.iterrows():
    team_id = team_row["id"]
    name = team_row["team_name"]
    fixtures_df.loc[fixtures_df["home_team_id"] == team_id, "team_1_name"] = name
    fixtures_df.loc[fixtures_df["away_team_id"] == team_id, "team_2_name"] = name

In [6]:
fixtures_df.dropna().to_csv("data/2026/fixtures_preprocessed.csv", index=False)

In [15]:
fixture_df_teams = fixtures_df.dropna()["team_1_name"].unique().tolist()
fixture_df_teams

['Mexico',
 'South Korea',
 'Canada',
 'USA',
 'Qatar',
 'Brazil',
 'Haiti',
 'Australia',
 'Germany',
 'Netherlands',
 "Côte d'Ivoire",
 'Sweden',
 'Spain',
 'Belgium',
 'Saudi Arabia',
 'IR Iran',
 'France',
 'Iraq',
 'Argentina',
 'Austria',
 'Portugal',
 'England',
 'Ghana',
 'Uzbekistan',
 'Czechia',
 'Switzerland',
 'Scotland',
 'Turkey',
 'Ecuador',
 'Tunisia',
 'Uruguay',
 'New Zealand',
 'Norway',
 'Jordan',
 'Panama',
 'Colombia',
 'Bosnia and Herzegovina',
 'Morocco',
 'South Africa',
 'Curaçao',
 'Japan',
 'Paraguay',
 'Senegal',
 'Cabo Verde',
 'Egypt',
 'Croatia',
 'DR Congo',
 'Algeria']

In [16]:
import json

with open("iwan/preprocessed_data/2026_featurised_squads.json", "r") as f:
    featurised_squads = json.load(f)

In [17]:
expected_teams = list(featurised_squads.keys())
for t in fixture_df_teams:
    if t not in expected_teams:
        print(t)

IR Iran
Curaçao
Cabo Verde